[package]
name = "darkest"
version = "0.1.0"
authors = ["inhibitor"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.31.0"
gl = "0.10.0"
