[package]
name = "darkest"
version = "0.1.0"
authors = ["inhibitor"]
edition = "2018"
build = "build.rs"

[dependencies]
gl = { path = "lib/gl" }
cgmath = "*"

[dependencies.sdl2]
version = "0.31.0"

